
// FAQ toggle
document.querySelectorAll('.faq-item').forEach(item => {
    item.addEventListener('click', () => item.classList.toggle('open'));
});

// ── I18N ──────────────────────────────────────────────────────────────────
const LANG_META = {
    id: { flag: '🇮🇩', label: 'ID' },
    en: { flag: '🇬🇧', label: 'EN' },
    ja: { flag: '🇯🇵', label: 'JA' },
    es: { flag: '🇪🇸', label: 'ES' },
    zh: { flag: '🇨🇳', label: 'ZH' },
};

const T = {
    en: {
        page_title: 'Waltly — Simple & honest daily budget',
        nav_features: 'Features', nav_how: 'How it works', nav_pricing: 'Pricing', nav_faq: 'FAQ', nav_download: 'Download',
        hero_eyebrow: 'Your wallet, your rules.',
        hero_h1: 'Your money. <span class="hl">Clear</span> and in control.',
        hero_sub: 'Waltly tracks your income, expenses, and budgets — no bank access required, no account needed.',
        hero_cta_dl: 'Download on App Store', hero_cta_how: 'See how it works →',
        hero_reviews: '4.9 — 2,300+ reviews', hero_price: 'Free · One-time Pro',
        badge_income: 'INCOME · Today', badge_budget: 'BUDGET', badge_on_track: 'On track 🎯', badge_food: 'FOOD',
        proof_users: 'Active users', proof_rating: 'App Store rating', proof_tx: 'Transactions logged', proof_pro: 'One-time Pro', proof_bank: 'Bank access needed',
        feat_eye: 'Features',
        feat_title: 'Everything you need to <span class="hl-dark">count money</span> — nothing you don\'t.',
        feat_sub: 'Built iOS-first with the home widget, Control Center shortcut, and Indonesian-friendly UX — all in one app.',
        f1_pill: 'Hero feature', f1_h3: 'Log a transaction in 2 seconds flat.', f1_p: 'Tap the Control Center tile or your home screen widget, type the amount, done. No more "I\'ll log it later" excuses.',
        f2_pill: 'Multi-currency', f2_h3: 'One app. Every wallet.', f2_p: 'Cash, bank accounts, e-wallets — track them all in one place. Each wallet keeps its own currency, so nothing gets mixed up.',
        f3_pill: 'Budget traffic lights', f3_h3: 'Green, amber, red — at a glance.', f3_p: 'Every budget card shows where you stand instantly. No math, no mental gymnastics.',
        f4_pill: 'Trip & event funds', f4_h3: 'Envelopes for Bali, weddings, whatever.', f4_p: 'One-off funds that live alongside monthly budgets. Close them when the trip\'s done.',
        f5_pill: 'Home widget', f5_h3: 'Today\'s spend on your home screen.', f5_p: 'Medium + small widgets for lock screen, home screen, and StandBy.',
        f6_pill: 'Private by default', f6_h3: 'Your money stays on your phone. Period.', f6_p: 'No bank logins, no screen-scraping. Waltly runs fully on-device — with iCloud backup that\'s encrypted end-to-end, powered by Apple CloudKit.',
        how_eye: 'How it works',
        how_title: 'Three steps. <span class="hl-dark">That\'s it.</span>',
        s1_h4: 'Set your monthly budget', s1_p: 'Pick categories that matter — Food, Transit, Bills — and assign a rupiah cap to each. Recurring templates do the heavy lifting every month.',
        s2_h4: 'Log as you spend', s2_p: 'Widget, Control Center, or in-app — two taps and it\'s in. No receipt scanning, no bank linking, no friction.',
        s3_h4: 'Stay on track', s3_p: 'Green-amber-red cards tell you where you stand. Swipe months, jump to today, or scroll back to see where it all went.',
        tess_eye: 'Testimonials', tess_title: 'What early users are saying.',
        t1_q: '"Finally a budget app that uses Rupiah properly and isn\'t trying to connect to my bank. The Control Center shortcut is genius — I log every gojek instantly."', t1_role: 'Jakarta · Designer',
        t2_q: '"The simplest budget app I\'ve ever tried. Pay once, no monthly subscriptions. The green-yellow-red colors instantly show how your budget is doing."', t2_role: 'Surabaya · Freelancer',
        t3_q: '"Used YNAB for years, switched over because subscription fatigue is real. Waltly does 90% of what I needed, beautifully, for the price of one coffee."', t3_role: 'Bandung · PM',
        price_eye: 'Pricing',
        price_title: 'Pay once. <span class="hl-dark">Own it forever.</span>',
        price_sub: 'No subscriptions. No "lifetime deal" gimmicks. Just pay once and you own it.',
        free_name: 'Free', free_sub: 'Forever. One wallet, unlimited transactions.',
        free_f1: 'Unlimited transactions', free_f2: '1 wallet, 5 categories', free_f3: 'Monthly budget + summary', free_f4: 'Bahasa Indonesia + English',
        free_btn: 'Get Waltly Free',
        pro_name: 'Pro Unlock', pro_sub: 'One-time. Launch price — ends 31 May 2026.',
        pro_f1: 'Everything in Free', pro_f2: 'Unlimited wallets & categories', pro_f3: 'Widgets + Control Center quick-add', pro_f4: 'Trip & event funds', pro_f5: 'Recurring budget templates', pro_f6: 'iCloud sync (E2E encrypted)', pro_f7: 'CSV export',
        pro_btn: 'Unlock Pro — Rp 79,000',
        faq_eye: 'FAQ', faq_title: 'Questions, answered.',
        faq1_q: 'Does Waltly connect to my bank?', faq1_a: 'No — and that\'s by design. Indonesian banks don\'t offer clean developer APIs, and screen-scraping is fragile and risky. You log transactions manually (2 taps via widget), so your money data never leaves your phone.',
        faq2_q: 'Is it really one-time payment?', faq2_a: 'Yes. Pay Rp 79,000 once and Pro is yours forever — on every iOS device signed in with your Apple ID. No renewal, no surprise charges, no feature held hostage by a subscription.',
        faq3_q: 'Do you support Android?', faq3_a: 'Not yet. Waltly is built iOS-first to take full advantage of widgets, Control Center, StandBy, and SwiftUI polish. Android is on the roadmap for 2027.',
        faq4_q: 'Can I export my data?', faq4_a: 'Absolutely. Pro users can export full transaction history as CSV at any time. Your data is yours — if you ever leave, you walk out with everything.',
        faq5_q: 'What languages are supported?', faq5_a: 'Bahasa Indonesia and English at launch. Every label, tooltip, and copy string is written natively in both — not machine-translated. More languages coming based on user votes.',
        final_h2: 'Start tracking your money.<br>Today.',
        final_p: 'Free forever. Upgrade to Pro when you\'re ready. Works on iPhone and iPad.',
        final_btn: 'Download on the App Store',
        legal_eye: 'Legal',
        privacy_title: 'Privacy Policy', privacy_updated: 'Last updated: April 18, 2026',
        privacy_p1: 'Waltly does not collect, store, or transmit any personal data to external servers.',
        privacy_p2: 'All financial data you enter — transactions, wallets, budgets, and goals — is stored locally on your device using Apple\'s native frameworks. Your data never leaves your device unless you explicitly export it yourself.',
        privacy_nouse_h: 'What we do not use', privacy_li1: 'Analytics or tracking tools', privacy_li2: 'Advertising networks', privacy_li3: 'Third-party SDKs that collect data', privacy_li4: 'Crash reporting services that transmit personal information',
        privacy_noacct_h: 'No account required', privacy_noacct_p: 'We do not require you to create an account.',
        privacy_support_h: 'Support contact', privacy_support_p: 'If you contact us for support via email, we will use your email address solely to respond to your inquiry and will not store it beyond that conversation.',
        privacy_apple_h: 'Apple & the App Store', privacy_apple_p: 'Apple may collect certain usage data through the App Store as outlined in Apple\'s own privacy policy, which is independent of Waltly.',
        privacy_contact: 'For questions, contact:',
        terms_title: 'Terms of Use', terms_updated: 'Last updated: April 18, 2026',
        terms_intro: 'By downloading or using Waltly, you agree to these terms.',
        terms_license_h: 'License', terms_license_p: 'Waltly grants you a personal, non-transferable, non-exclusive license to use the app on your Apple devices. You may not copy, modify, reverse engineer, or distribute the app.',
        terms_data_h: 'Your data', terms_data_p: 'All data you enter into Waltly belongs to you. We have no access to it. You are responsible for maintaining your own backups.',
        terms_advice_h: 'No financial advice', terms_advice_p: 'Waltly is a personal budgeting tool. Nothing in the app constitutes financial, investment, or legal advice. Always consult a qualified professional for financial decisions.',
        terms_warranty_h: 'Disclaimer of warranties', terms_warranty_p: 'Waltly is provided "as is" without warranties of any kind. We do not guarantee that the app will be error-free or uninterrupted.',
        terms_liability_h: 'Limitation of liability', terms_liability_p: 'To the maximum extent permitted by law, Waltly and its developer shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app.',
        terms_changes_h: 'Changes to these terms', terms_changes_p: 'We may update these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.',
        terms_contact: 'Contact:',
        foot_privacy: 'Privacy', foot_terms: 'Terms', foot_support: 'Support', foot_twitter: 'Twitter', foot_ig: 'Instagram',
    },
    id: {
        page_title: 'Waltly — Budget harian yang simpel & jujur',
        nav_features: 'Fitur', nav_how: 'Cara kerja', nav_pricing: 'Harga', nav_faq: 'FAQ', nav_download: 'Unduh',
        hero_eyebrow: 'Dompetmu, aturanmu.',
        hero_h1: 'Uangmu. <span class="hl">Jelas</span> dan terkendali.',
        hero_sub: 'Waltly melacak pemasukan, pengeluaran, dan anggaranmu — tanpa akses bank, tanpa perlu akun.',
        hero_cta_dl: 'Download di App Store', hero_cta_how: 'Lihat cara kerjanya →',
        hero_reviews: '4.9 — 2.300+ ulasan', hero_price: 'Gratis · Bayar Sekali Pro',
        badge_income: 'PEMASUKAN · Hari ini', badge_budget: 'BUDGET', badge_on_track: 'Sesuai target 🎯', badge_food: 'MAKANAN',
        proof_users: 'Pengguna aktif', proof_rating: 'Rating App Store', proof_tx: 'Transaksi tercatat', proof_pro: 'Pro bayar sekali', proof_bank: 'Akses bank diperlukan',
        feat_eye: 'Fitur',
        feat_title: 'Semua yang kamu butuhkan untuk <span class="hl-dark">hitung duit</span> — tidak lebih.',
        feat_sub: 'Dibangun iOS-first dengan widget home, shortcut Control Center, dan UX ramah Indonesia — semua dalam satu aplikasi.',
        f1_pill: 'Fitur unggulan', f1_h3: 'Catat transaksi dalam 2 detik.', f1_p: 'Ketuk tile Control Center atau widget home screen, ketik jumlahnya, selesai. Tidak ada lagi alasan "nanti aja dicatatnya".',
        f2_pill: 'Multi-mata uang', f2_h3: 'Satu aplikasi. Semua dompet.', f2_p: 'Uang tunai, rekening bank, e-wallet — lacak semuanya di satu tempat. Setiap dompet menyimpan mata uangnya sendiri, jadi tidak ada yang tercampur.',
        f3_pill: 'Lampu lalu lintas budget', f3_h3: 'Hijau, kuning, merah — sekilas langsung paham.', f3_p: 'Setiap kartu budget menunjukkan posisimu saat ini secara instan. Tidak perlu hitung-hitungan.',
        f4_pill: 'Dana perjalanan & acara', f4_h3: 'Amplop untuk Bali, pernikahan, apapun.', f4_p: 'Dana satu kali yang hidup berdampingan dengan budget bulanan. Tutup saat perjalanan selesai.',
        f5_pill: 'Widget home screen', f5_h3: 'Pengeluaran hari ini di layar utamamu.', f5_p: 'Widget medium + kecil untuk lock screen, home screen, dan StandBy.',
        f6_pill: 'Privat secara default', f6_h3: 'Uangmu tetap di ponselmu. Titik.', f6_p: 'Tidak ada login bank, tidak ada screen-scraping. Waltly berjalan sepenuhnya on-device — dengan backup iCloud yang terenkripsi end-to-end, didukung oleh Apple CloudKit.',
        how_eye: 'Cara kerja',
        how_title: 'Tiga langkah. <span class="hl-dark">Itu saja.</span>',
        s1_h4: 'Atur budget bulananmu', s1_p: 'Pilih kategori yang penting — Makanan, Transportasi, Tagihan — dan tetapkan batas rupiah untuk masing-masing. Template berulang mengurus semuanya setiap bulan.',
        s2_h4: 'Catat saat kamu belanja', s2_p: 'Widget, Control Center, atau langsung di aplikasi — dua ketukan dan sudah tercatat. Tidak perlu scan struk, tidak perlu hubungkan bank.',
        s3_h4: 'Tetap sesuai rencana', s3_p: 'Kartu hijau-kuning-merah memberitahumu posisimu. Geser bulan, loncat ke hari ini, atau gulir ke belakang untuk melihat ke mana uangmu pergi.',
        tess_eye: 'Testimoni', tess_title: 'Yang dikatakan pengguna awal.',
        t1_q: '"Akhirnya ada aplikasi budget yang pakai Rupiah dengan benar dan nggak nyoba konek ke rekening bankku. Shortcut Control Center-nya jenius — langsung catat setiap gojek."', t1_role: 'Jakarta · Designer',
        t2_q: '"Aplikasi budget paling simpel yang pernah saya coba. Satu kali bayar, nggak ada langganan tiap bulan. Warna hijau-kuning-merah-nya langsung kelihatan budget-nya gimana."', t2_role: 'Surabaya · Freelancer',
        t3_q: '"Pakai YNAB bertahun-tahun, pindah karena lelah berlangganan. Waltly memenuhi 90% kebutuhanku, dengan tampilan indah, seharga satu kopi."', t3_role: 'Bandung · PM',
        price_eye: 'Harga',
        price_title: 'Bayar sekali. <span class="hl-dark">Pakai selamanya.</span>',
        price_sub: 'Tanpa langganan. Tanpa gimmick "lifetime deal". Bayar sekali dan milikmu selamanya.',
        free_name: 'Gratis', free_sub: 'Selamanya. Satu wallet, transaksi tak terbatas.',
        free_f1: 'Transaksi tak terbatas', free_f2: '1 wallet, 5 kategori', free_f3: 'Budget bulanan + ringkasan', free_f4: 'Bahasa Indonesia + English',
        free_btn: 'Dapatkan Waltly Gratis',
        pro_name: 'Pro Unlock', pro_sub: 'Satu kali bayar. Harga peluncuran — berakhir 31 Mei 2026.',
        pro_f1: 'Semua fitur Gratis', pro_f2: 'Wallet & kategori tak terbatas', pro_f3: 'Widget + quick-add Control Center', pro_f4: 'Dana perjalanan & acara', pro_f5: 'Template budget berulang', pro_f6: 'iCloud sync (terenkripsi E2E)', pro_f7: 'Ekspor CSV',
        pro_btn: 'Buka Pro — Rp 79.000',
        faq_eye: 'FAQ', faq_title: 'Pertanyaan, terjawab.',
        faq1_q: 'Apakah Waltly terhubung ke rekening bankku?', faq1_a: 'Tidak — dan itu memang disengaja. Bank Indonesia tidak menawarkan API developer yang bersih, dan screen-scraping itu rapuh dan berisiko. Kamu mencatat transaksi secara manual (2 ketukan via widget), sehingga data keuanganmu tidak pernah meninggalkan ponselmu.',
        faq2_q: 'Apakah benar-benar bayar sekali?', faq2_a: 'Ya. Bayar Rp 79.000 sekali dan Pro milikmu selamanya — di setiap perangkat iOS yang masuk dengan Apple ID-mu. Tidak ada perpanjangan, tidak ada biaya kejutan, tidak ada fitur yang ditahan oleh langganan.',
        faq3_q: 'Apakah mendukung Android?', faq3_a: 'Belum. Waltly dibangun iOS-first untuk memanfaatkan sepenuhnya widget, Control Center, StandBy, dan polish SwiftUI. Android ada di roadmap untuk 2027.',
        faq4_q: 'Bisakah saya mengekspor data saya?', faq4_a: 'Tentu. Pengguna Pro dapat mengekspor riwayat transaksi lengkap sebagai CSV kapan saja. Data kamu adalah milikmu — jika kamu pergi, kamu keluar dengan semuanya.',
        faq5_q: 'Bahasa apa saja yang didukung?', faq5_a: 'Bahasa Indonesia dan Inggris saat peluncuran. Setiap label, tooltip, dan teks ditulis secara native dalam keduanya — bukan terjemahan mesin. Bahasa lain menyusul berdasarkan suara pengguna.',
        final_h2: 'Mulai hitung duit kamu.<br>Hari ini.',
        final_p: 'Gratis selamanya. Upgrade ke Pro saat kamu siap. Tersedia di iPhone dan iPad.',
        final_btn: 'Download di App Store',
        legal_eye: 'Legal',
        privacy_title: 'Kebijakan Privasi', privacy_updated: 'Terakhir diperbarui: 18 April 2026',
        privacy_p1: 'Waltly tidak mengumpulkan, menyimpan, atau mengirimkan data pribadi apa pun ke server eksternal.',
        privacy_p2: 'Semua data keuangan yang kamu masukkan — transaksi, dompet, anggaran, dan tujuan — disimpan secara lokal di perangkatmu menggunakan framework asli Apple. Datamu tidak pernah meninggalkan perangkat kecuali kamu mengekspornya sendiri.',
        privacy_nouse_h: 'Yang tidak kami gunakan', privacy_li1: 'Alat analitik atau pelacakan', privacy_li2: 'Jaringan iklan', privacy_li3: 'SDK pihak ketiga yang mengumpulkan data', privacy_li4: 'Layanan pelaporan crash yang mengirimkan informasi pribadi',
        privacy_noacct_h: 'Tidak perlu akun', privacy_noacct_p: 'Kami tidak mengharuskan kamu membuat akun.',
        privacy_support_h: 'Kontak dukungan', privacy_support_p: 'Jika kamu menghubungi kami melalui email, kami hanya akan menggunakan alamat emailmu untuk merespons pertanyaanmu dan tidak akan menyimpannya setelah percakapan selesai.',
        privacy_apple_h: 'Apple & App Store', privacy_apple_p: 'Apple dapat mengumpulkan data penggunaan tertentu melalui App Store sesuai kebijakan privasi Apple sendiri, yang terpisah dari Waltly.',
        privacy_contact: 'Untuk pertanyaan, hubungi:',
        terms_title: 'Syarat Penggunaan', terms_updated: 'Terakhir diperbarui: 18 April 2026',
        terms_intro: 'Dengan mengunduh atau menggunakan Waltly, kamu menyetujui syarat-syarat ini.',
        terms_license_h: 'Lisensi', terms_license_p: 'Waltly memberimu lisensi penggunaan pribadi, tidak dapat dipindahtangankan, dan non-eksklusif untuk menggunakan aplikasi di perangkat Apple-mu. Kamu tidak boleh menyalin, memodifikasi, merekayasa balik, atau mendistribusikan aplikasi.',
        terms_data_h: 'Data kamu', terms_data_p: 'Semua data yang kamu masukkan ke Waltly adalah milikmu. Kami tidak memiliki akses ke sana. Kamu bertanggung jawab untuk menjaga cadangan datamu sendiri.',
        terms_advice_h: 'Bukan saran keuangan', terms_advice_p: 'Waltly adalah alat penganggaran pribadi. Tidak ada konten dalam aplikasi yang merupakan saran keuangan, investasi, atau hukum. Selalu konsultasikan dengan profesional berkualifikasi untuk keputusan keuangan.',
        terms_warranty_h: 'Penafian garansi', terms_warranty_p: 'Waltly disediakan "sebagaimana adanya" tanpa garansi apa pun. Kami tidak menjamin aplikasi bebas dari kesalahan atau tidak pernah terganggu.',
        terms_liability_h: 'Batasan tanggung jawab', terms_liability_p: 'Sejauh yang diizinkan hukum, Waltly dan pengembangnya tidak bertanggung jawab atas kerusakan tidak langsung, insidental, atau konsekuensial yang timbul dari penggunaan aplikasi.',
        terms_changes_h: 'Perubahan pada syarat ini', terms_changes_p: 'Kami dapat memperbarui syarat ini kapan saja. Penggunaan aplikasi yang berlanjut setelah perubahan berarti penerimaan syarat baru.',
        terms_contact: 'Kontak:',
        foot_privacy: 'Privasi', foot_terms: 'Syarat', foot_support: 'Dukungan', foot_twitter: 'Twitter', foot_ig: 'Instagram',
    },
    ja: {
        page_title: 'Waltly — シンプルで正直な毎日の家計管理',
        nav_features: '機能', nav_how: '使い方', nav_pricing: '料金', nav_faq: 'よくある質問', nav_download: 'ダウンロード',
        hero_eyebrow: 'あなたの財布、あなたのルール。',
        hero_h1: 'あなたのお金。<span class="hl">明確</span>にコントロール。',
        hero_sub: 'Waltly — 収入、支出、予算を管理。銀行アクセス不要、アカウント不要。',
        hero_cta_dl: 'App Storeでダウンロード', hero_cta_how: '使い方を見る →',
        hero_reviews: '4.9 — 2,300件以上のレビュー', hero_price: '無料 · 買い切りPro',
        badge_income: '収入 · 今日', badge_budget: '予算', badge_on_track: '順調 🎯', badge_food: '食費',
        proof_users: 'アクティブユーザー', proof_rating: 'App Storeレーティング', proof_tx: '記録された取引', proof_pro: '買い切りPro', proof_bank: '銀行アクセス不要',
        feat_eye: '機能',
        feat_title: 'お金を<span class="hl-dark">管理するために必要なもの</span>だけ、無駄なし。',
        feat_sub: 'ホームウィジェット、コントロールセンターショートカット、インドネシア向けUXを備えたiOS専用アプリ。',
        f1_pill: '主要機能', f1_h3: '2秒で取引を記録。', f1_p: 'コントロールセンターのタイルまたはホーム画面ウィジェットをタップ、金額を入力、完了。「あとで記録しよう」はもう不要。',
        f2_pill: 'マルチ通貨', f2_h3: '1つのアプリ。すべてのウォレット。', f2_p: '現金、銀行口座、電子マネー — すべてを一か所で管理。各ウォレットは独自の通貨を保持し、混乱しません。',
        f3_pill: '予算信号機', f3_h3: '緑・黄・赤 — ひと目でわかる。', f3_p: 'すべての予算カードが現在の状況を瞬時に表示。計算不要、頭を使わなくていい。',
        f4_pill: '旅行・イベント資金', f4_h3: 'バリ、結婚式など、何にでも使える封筒。', f4_p: '月次予算と並存する一時的な資金。旅行が終わったら閉じるだけ。',
        f5_pill: 'ホームウィジェット', f5_h3: '今日の支出をホーム画面で確認。', f5_p: 'ロック画面、ホーム画面、スタンバイ用の中・小ウィジェット。',
        f6_pill: 'プライバシー優先', f6_h3: 'あなたのお金はあなたのスマホに。それだけ。', f6_p: '銀行ログイン不要、スクリーンスクレイピングなし。完全オンデバイスで動作 — Apple CloudKit を使用した E2E 暗号化 iCloud バックアップ付き。',
        how_eye: '使い方',
        how_title: '3ステップ。<span class="hl-dark">それだけ。</span>',
        s1_h4: '月々の予算を設定', s1_p: '重要なカテゴリ（食費、交通費、光熱費）を選び、それぞれにルピア上限を設定。毎月の繰り返しテンプレートが作業を自動化。',
        s2_h4: '使うたびに記録', s2_p: 'ウィジェット、コントロールセンター、またはアプリ内 — 2タップで記録完了。レシートスキャンも銀行連携も不要。',
        s3_h4: '予算通りに進む', s3_p: '緑・黄・赤のカードで現在の状況を確認。月をスワイプしたり、今日に戻ったり、過去を振り返ったりできます。',
        tess_eye: 'ユーザーの声', tess_title: '初期ユーザーのレビュー。',
        t1_q: '「ついにルピアを正しく使い、銀行に接続しようとしないアプリが登場。コントロールセンターのショートカットは天才的 — すべての取引をすぐ記録できる。」', t1_role: 'ジャカルタ · デザイナー',
        t2_q: '「今まで試した中で最もシンプルな家計アプリ。一度払いでサブスク不要。緑・黄・赤の色で予算の状況がすぐわかる。」', t2_role: 'スラバヤ · フリーランサー',
        t3_q: '「YNABを何年も使っていたが、サブスク疲れで乗り換えた。Waltlyはコーヒー1杯の値段で、必要な機能の90%を美しく提供してくれる。」', t3_role: 'バンドン · PM',
        price_eye: '料金',
        price_title: '一度払い。<span class="hl-dark">永久に使える。</span>',
        price_sub: 'サブスクなし。「生涯プラン」のギミックなし。一度払えばあなたのもの。',
        free_name: '無料', free_sub: '永久。1ウォレット、取引数無制限。',
        free_f1: '取引数無制限', free_f2: '1ウォレット、5カテゴリ', free_f3: '月次予算 + サマリー', free_f4: 'インドネシア語 + 英語',
        free_btn: 'Waltlyを無料で入手',
        pro_name: 'Proアンロック', pro_sub: '一度払い。ローンチ価格 — 2026年5月31日まで。',
        pro_f1: '無料版のすべて', pro_f2: 'ウォレット・カテゴリ無制限', pro_f3: 'ウィジェット + コントロールセンター', pro_f4: '旅行・イベント資金', pro_f5: '繰り返し予算テンプレート', pro_f6: 'iCloudSync（E2E暗号化）', pro_f7: 'CSVエクスポート',
        pro_btn: 'Proをアンロック — Rp 79,000',
        faq_eye: 'よくある質問', faq_title: 'ご質問にお答えします。',
        faq1_q: 'Waltlyは銀行に接続しますか？', faq1_a: 'いいえ — それは意図的な設計です。インドネシアの銀行はクリーンな開発者APIを提供しておらず、スクリーンスクレイピングは脆弱でリスクがあります。ウィジェット経由の2タップで手動記録するため、お金のデータはスマホから外に出ません。',
        faq2_q: '本当に一度払いですか？', faq2_a: 'はい。Rp 79,000を一度払えば、Apple IDでサインインしたすべてのiOSデバイスでProが永久に使えます。更新不要、サプライズ課金なし。',
        faq3_q: 'Androidに対応していますか？', faq3_a: 'まだです。Waltlyはウィジェット、コントロールセンター、スタンバイ、SwiftUIの最大活用のためiOS専用で作られています。Androidは2027年のロードマップにあります。',
        faq4_q: 'データをエクスポートできますか？', faq4_a: 'もちろんです。Proユーザーはいつでも完全な取引履歴をCSVでエクスポートできます。データはあなたのもの — 退会してもすべて持ち出せます。',
        faq5_q: '対応言語は？', faq5_a: 'ローンチ時はインドネシア語と英語に対応。すべてのラベル、ツールチップ、テキストは機械翻訳ではなくネイティブに記述。ユーザーの投票に基づき他の言語も追加予定。',
        final_h2: 'お金の管理を始めよう。<br>今日から。',
        final_p: '永久無料。準備ができたらProにアップグレード。iPhoneとiPadで動作。',
        final_btn: 'App Storeでダウンロード',
        legal_eye: '法的情報',
        privacy_title: 'プライバシーポリシー', privacy_updated: '最終更新日：2026年4月18日',
        privacy_p1: 'Waltlyは、外部サーバーへの個人データの収集、保存、または送信を一切行いません。',
        privacy_p2: '取引、ウォレット、予算、目標などのすべての財務データは、Appleのネイティブフレームワークを使用してデバイス上にローカルに保存されます。ご自身でエクスポートしない限り、データはデバイスの外に出ることはありません。',
        privacy_nouse_h: '使用しないもの', privacy_li1: '分析またはトラッキングツール', privacy_li2: '広告ネットワーク', privacy_li3: 'データを収集するサードパーティSDK', privacy_li4: '個人情報を送信するクラッシュレポートサービス',
        privacy_noacct_h: 'アカウント不要', privacy_noacct_p: 'アカウントの作成は必要ありません。',
        privacy_support_h: 'サポートへのお問い合わせ', privacy_support_p: 'メールでサポートにお問い合わせいただいた場合、メールアドレスはご質問への返答にのみ使用し、会話終了後は保存しません。',
        privacy_apple_h: 'Apple・App Store', privacy_apple_p: 'AppleはApp Storeを通じて一定の使用データを収集する場合がありますが、これはWaltlyとは独立したApple自身のプライバシーポリシーに基づくものです。',
        privacy_contact: 'ご質問は以下までご連絡ください：',
        terms_title: '利用規約', terms_updated: '最終更新日：2026年4月18日',
        terms_intro: 'Waltlyをダウンロードまたは使用することで、これらの規約に同意したものとみなされます。',
        terms_license_h: 'ライセンス', terms_license_p: 'Waltlyは、Appleデバイスでのアプリ使用に対して、個人的・非譲渡・非独占的なライセンスを付与します。アプリのコピー、改変、リバースエンジニアリング、配布はできません。',
        terms_data_h: 'お客様のデータ', terms_data_p: 'Waltlyに入力したすべてのデータはお客様のものです。私たちはアクセスできません。バックアップの管理はお客様の責任です。',
        terms_advice_h: '投資・法律アドバイスではありません', terms_advice_p: 'Waltlyは個人向け予算管理ツールです。アプリ内のいかなる内容も、財務・投資・法律上のアドバイスを構成するものではありません。財務上の判断は必ず専門家にご相談ください。',
        terms_warranty_h: '保証の免責', terms_warranty_p: 'Waltlyは「現状のまま」提供され、いかなる保証もありません。アプリがエラーなく継続的に動作することを保証するものではありません。',
        terms_liability_h: '責任の制限', terms_liability_p: '法律で認められる最大限の範囲において、Waltlyおよびその開発者は、アプリの使用に起因する間接的・偶発的・結果的損害について責任を負いません。',
        terms_changes_h: '規約の変更', terms_changes_p: '規約はいつでも更新される場合があります。変更後にアプリを使用し続けることで、新しい規約に同意したものとみなされます。',
        terms_contact: 'お問い合わせ：',
        foot_privacy: 'プライバシー', foot_terms: '利用規約', foot_support: 'サポート', foot_twitter: 'Twitter', foot_ig: 'Instagram',
    },
    es: {
        page_title: 'Waltly — Presupuesto diario simple y honesto',
        nav_features: 'Funciones', nav_how: 'Cómo funciona', nav_pricing: 'Precios', nav_faq: 'Preguntas', nav_download: 'Descargar',
        hero_eyebrow: 'Tu cartera, tus reglas.',
        hero_h1: 'Tu dinero. <span class="hl">Claro</span> y bajo control.',
        hero_sub: 'Waltly registra tus ingresos, gastos y presupuestos — sin acceso bancario, sin necesidad de cuenta.',
        hero_cta_dl: 'Descargar en App Store', hero_cta_how: 'Ver cómo funciona →',
        hero_reviews: '4.9 — más de 2.300 reseñas', hero_price: 'Gratis · Pro de pago único',
        badge_income: 'INGRESOS · Hoy', badge_budget: 'PRESUPUESTO', badge_on_track: 'Al día 🎯', badge_food: 'COMIDA',
        proof_users: 'Usuarios activos', proof_rating: 'Puntuación App Store', proof_tx: 'Transacciones registradas', proof_pro: 'Pro pago único', proof_bank: 'Acceso bancario necesario',
        feat_eye: 'Funciones',
        feat_title: 'Todo lo que necesitas para <span class="hl-dark">controlar tu dinero</span> — nada más.',
        feat_sub: 'Construido iOS-first con widget de inicio, acceso rápido al Centro de Control y UX amigable para Indonesia — todo en una sola app.',
        f1_pill: 'Función estrella', f1_h3: 'Registra una transacción en 2 segundos.', f1_p: 'Toca el acceso en Centro de Control o tu widget de pantalla de inicio, escribe el monto, listo. Se acabaron las excusas de "lo anoto después".',
        f2_pill: 'Multidivisa', f2_h3: 'Una app. Todas las carteras.', f2_p: 'Efectivo, cuentas bancarias, billeteras electrónicas — rastrea todo en un solo lugar. Cada cartera mantiene su propia moneda, nada se mezcla.',
        f3_pill: 'Semáforo de presupuesto', f3_h3: 'Verde, amarillo, rojo — de un vistazo.', f3_p: 'Cada tarjeta de presupuesto muestra tu situación al instante. Sin cálculos, sin esfuerzo mental.',
        f4_pill: 'Fondos de viaje y eventos', f4_h3: 'Sobres para Bali, bodas, lo que sea.', f4_p: 'Fondos únicos que conviven con tu presupuesto mensual. Ciérralos cuando termine el viaje.',
        f5_pill: 'Widget de inicio', f5_h3: 'Tu gasto de hoy en la pantalla de inicio.', f5_p: 'Widgets medianos y pequeños para pantalla de bloqueo, inicio y StandBy.',
        f6_pill: 'Privado por defecto', f6_h3: 'Tu dinero se queda en tu teléfono. Punto.', f6_p: 'Sin inicios de sesión bancarios, sin screen-scraping. Waltly funciona completamente en el dispositivo — con backup iCloud cifrado de extremo a extremo, impulsado por Apple CloudKit.',
        how_eye: 'Cómo funciona',
        how_title: 'Tres pasos. <span class="hl-dark">Eso es todo.</span>',
        s1_h4: 'Establece tu presupuesto mensual', s1_p: 'Elige las categorías que importan — Comida, Transporte, Facturas — y asigna un límite en rupias a cada una. Las plantillas recurrentes hacen el trabajo pesado cada mes.',
        s2_h4: 'Registra al gastar', s2_p: 'Widget, Centro de Control o en la app — dos toques y listo. Sin escanear recibos, sin vincular bancos, sin fricciones.',
        s3_h4: 'Mantente al día', s3_p: 'Las tarjetas verde-amarillo-rojo te dicen cómo vas. Desliza meses, salta a hoy o desplázate para ver en qué se fue todo.',
        tess_eye: 'Testimonios', tess_title: 'Lo que dicen los primeros usuarios.',
        t1_q: '"Por fin una app de presupuesto que usa Rupias correctamente y no intenta conectarse a mi banco. El acceso rápido del Centro de Control es genial — registro cada gasto al instante."', t1_role: 'Yakarta · Diseñador',
        t2_q: '"La app de presupuesto más simple que he probado. Pago único, sin suscripciones mensuales. Los colores verde-amarillo-rojo muestran al instante cómo va tu presupuesto."', t2_role: 'Surabaya · Freelancer',
        t3_q: '"Usé YNAB durante años, me cambié porque el cansancio de las suscripciones es real. Waltly cubre el 90% de lo que necesitaba, de forma hermosa, por el precio de un café."', t3_role: 'Bandung · PM',
        price_eye: 'Precios',
        price_title: 'Paga una vez. <span class="hl-dark">Úsalo siempre.</span>',
        price_sub: 'Sin suscripciones. Sin trucos de "oferta de por vida". Solo paga una vez y es tuyo.',
        free_name: 'Gratis', free_sub: 'Para siempre. Una cartera, transacciones ilimitadas.',
        free_f1: 'Transacciones ilimitadas', free_f2: '1 cartera, 5 categorías', free_f3: 'Presupuesto mensual + resumen', free_f4: 'Bahasa Indonesia + Inglés',
        free_btn: 'Obtener Waltly gratis',
        pro_name: 'Pro Unlock', pro_sub: 'Pago único. Precio de lanzamiento — termina el 31 de mayo de 2026.',
        pro_f1: 'Todo lo de Gratis', pro_f2: 'Carteras y categorías ilimitadas', pro_f3: 'Widgets + acceso rápido Centro de Control', pro_f4: 'Fondos de viaje y eventos', pro_f5: 'Plantillas de presupuesto recurrentes', pro_f6: 'Sync iCloud (cifrado E2E)', pro_f7: 'Exportar CSV',
        pro_btn: 'Desbloquear Pro — Rp 79.000',
        faq_eye: 'Preguntas', faq_title: 'Preguntas, respondidas.',
        faq1_q: 'Waltly se conecta a mi banco?', faq1_a: 'No — y eso es intencional. Los bancos indonesios no ofrecen APIs limpias para desarrolladores, y el screen-scraping es frágil y arriesgado. Registras transacciones manualmente (2 toques vía widget), por lo que tus datos nunca salen de tu teléfono.',
        faq2_q: '¿Es realmente un pago único?', faq2_a: 'Sí. Paga Rp 79.000 una vez y Pro es tuyo para siempre — en todos los dispositivos iOS con tu Apple ID. Sin renovaciones, sin cargos sorpresa.',
        faq3_q: '¿Soporta Android?', faq3_a: 'Todavía no. Waltly está construido iOS-first para aprovechar al máximo los widgets, Centro de Control, StandBy y SwiftUI. Android está en el roadmap para 2027.',
        faq4_q: '¿Puedo exportar mis datos?', faq4_a: 'Por supuesto. Los usuarios Pro pueden exportar el historial completo de transacciones en CSV en cualquier momento. Tus datos son tuyos — si te vas, te llevas todo.',
        faq5_q: '¿Qué idiomas están disponibles?', faq5_a: 'Bahasa Indonesia e inglés en el lanzamiento. Cada etiqueta, tooltip y texto está escrito nativamente en ambos — no traducido por máquina. Más idiomas según los votos de los usuarios.',
        final_h2: 'Empieza a controlar tu dinero.<br>Hoy.',
        final_p: 'Gratis para siempre. Actualiza a Pro cuando estés listo. Funciona en iPhone y iPad.',
        final_btn: 'Descargar en App Store',
        legal_eye: 'Legal',
        privacy_title: 'Política de privacidad', privacy_updated: 'Última actualización: 18 de abril de 2026',
        privacy_p1: 'Waltly no recopila, almacena ni transmite ningún dato personal a servidores externos.',
        privacy_p2: 'Todos los datos financieros que introduces — transacciones, carteras, presupuestos y objetivos — se almacenan localmente en tu dispositivo utilizando los marcos nativos de Apple. Tus datos nunca salen de tu dispositivo a menos que los exportes tú mismo.',
        privacy_nouse_h: 'Lo que no usamos', privacy_li1: 'Herramientas de análisis o seguimiento', privacy_li2: 'Redes publicitarias', privacy_li3: 'SDKs de terceros que recopilan datos', privacy_li4: 'Servicios de informes de fallos que transmiten información personal',
        privacy_noacct_h: 'Sin cuenta requerida', privacy_noacct_p: 'No te pedimos que crees una cuenta.',
        privacy_support_h: 'Contacto de soporte', privacy_support_p: 'Si nos contactas por soporte a través de correo electrónico, usaremos tu dirección únicamente para responder a tu consulta y no la almacenaremos más allá de esa conversación.',
        privacy_apple_h: 'Apple y la App Store', privacy_apple_p: 'Apple puede recopilar ciertos datos de uso a través de la App Store según su propia política de privacidad, la cual es independiente de Waltly.',
        privacy_contact: 'Para preguntas, contáctanos:',
        terms_title: 'Términos de uso', terms_updated: 'Última actualización: 18 de abril de 2026',
        terms_intro: 'Al descargar o usar Waltly, aceptas estos términos.',
        terms_license_h: 'Licencia', terms_license_p: 'Waltly te otorga una licencia personal, intransferible y no exclusiva para usar la aplicación en tus dispositivos Apple. No puedes copiar, modificar, realizar ingeniería inversa ni distribuir la aplicación.',
        terms_data_h: 'Tus datos', terms_data_p: 'Todos los datos que introduces en Waltly te pertenecen. No tenemos acceso a ellos. Eres responsable de mantener tus propias copias de seguridad.',
        terms_advice_h: 'Sin asesoramiento financiero', terms_advice_p: 'Waltly es una herramienta de presupuesto personal. Nada en la aplicación constituye asesoramiento financiero, de inversión o legal. Siempre consulta a un profesional cualificado para las decisiones financieras.',
        terms_warranty_h: 'Exclusión de garantías', terms_warranty_p: 'Waltly se proporciona "tal cual" sin garantías de ningún tipo. No garantizamos que la aplicación esté libre de errores o sea ininterrumpida.',
        terms_liability_h: 'Limitación de responsabilidad', terms_liability_p: 'En la máxima medida permitida por la ley, Waltly y su desarrollador no serán responsables de ningún daño indirecto, incidental o consecuente derivado del uso de la aplicación.',
        terms_changes_h: 'Cambios en estos términos', terms_changes_p: 'Podemos actualizar estos términos en cualquier momento. El uso continuado de la aplicación después de los cambios implica la aceptación de los nuevos términos.',
        terms_contact: 'Contacto:',
        foot_privacy: 'Privacidad', foot_terms: 'Términos', foot_support: 'Soporte', foot_twitter: 'Twitter', foot_ig: 'Instagram',
    },
    zh: {
        page_title: 'Waltly — 简单诚实的日常记账应用',
        nav_features: '功能', nav_how: '如何使用', nav_pricing: '定价', nav_faq: '常见问题', nav_download: '下载',
        hero_eyebrow: '你的钱包，你做主。',
        hero_h1: '你的钱。<span class="hl">清晰</span>掌控。',
        hero_sub: 'Waltly 追踪你的收入、支出和预算 — 无需银行授权，无需注册账户。',
        hero_cta_dl: '在 App Store 下载', hero_cta_how: '了解使用方式 →',
        hero_reviews: '4.9 — 2,300+ 条评价', hero_price: '免费 · 一次性 Pro',
        badge_income: '收入 · 今天', badge_budget: '预算', badge_on_track: '按计划进行 🎯', badge_food: '餐饮',
        proof_users: '活跃用户', proof_rating: 'App Store 评分', proof_tx: '已记录交易', proof_pro: 'Pro 一次付费', proof_bank: '需要银行访问',
        feat_eye: '功能',
        feat_title: '你需要的<span class="hl-dark">记账功能</span>，一个不少，一个不多。',
        feat_sub: 'iOS 优先打造，内置主屏幕小组件、控制中心快捷方式和印尼友好的用户体验，全在一个应用中。',
        f1_pill: '核心功能', f1_h3: '2 秒记录一笔交易。', f1_p: '点击控制中心图标或主屏幕小组件，输入金额，完成。再也没有"等会儿再记"的借口。',
        f2_pill: '多币种', f2_h3: '一个应用。所有钱包。', f2_p: '现金、银行账户、电子钱包 — 在一处追踪所有资产。每个钱包保留自己的币种，互不混淆。',
        f3_pill: '预算交通灯', f3_h3: '绿、黄、红 — 一眼看清。', f3_p: '每张预算卡片即时显示你的消费状况，无需计算，一目了然。',
        f4_pill: '旅行与活动基金', f4_h3: '为巴厘岛、婚礼等设置专属信封。', f4_p: '与月度预算并存的一次性基金，活动结束后关闭即可。',
        f5_pill: '主屏幕小组件', f5_h3: '今日支出显示在主屏幕。', f5_p: '锁屏、主屏幕和待机模式的中小尺寸小组件。',
        f6_pill: '默认隐私保护', f6_h3: '你的钱留在你的手机上。就这样。', f6_p: '无需银行登录，无屏幕抓取。完全本地运行 — 由 Apple CloudKit 提供支持的端到端加密 iCloud 备份。',
        how_eye: '如何使用',
        how_title: '三个步骤。<span class="hl-dark">就这些。</span>',
        s1_h4: '设置月度预算', s1_p: '选择重要分类 — 餐饮、交通、账单 — 并为每项设置卢比上限。每月的循环模板会自动处理。',
        s2_h4: '消费时记录', s2_p: '小组件、控制中心或应用内 — 两次点击即可完成。无需扫描收据，无需关联银行。',
        s3_h4: '保持正轨', s3_p: '绿黄红卡片告诉你当前状态。滑动月份、跳到今天，或向后滚动查看资金去向。',
        tess_eye: '用户评价', tess_title: '早期用户的反馈。',
        t1_q: '"终于有一款正确使用卢比并且不尝试连接我银行账户的预算应用。控制中心快捷方式太聪明了 — 每笔消费都能即时记录。"', t1_role: '雅加达 · 设计师',
        t2_q: '"我用过最简单的预算应用。一次付费，没有月度订阅。绿黄红颜色让你一眼看出预算状况。"', t2_role: '泗水 · 自由职业者',
        t3_q: '"用了多年 YNAB，因为订阅疲劳而转过来。HWaltly 用一杯咖啡的价格，美观地满足了我 90% 的需求。"', t3_role: '万隆 · 产品经理',
        price_eye: '定价',
        price_title: '一次付费。<span class="hl-dark">永久拥有。</span>',
        price_sub: '无订阅。无"终身套餐"噱头。一次付费，永久归你所有。',
        free_name: '免费版', free_sub: '永久免费。一个钱包，无限交易。',
        free_f1: '无限交易记录', free_f2: '1 个钱包，5 个分类', free_f3: '月度预算 + 摘要', free_f4: '印尼语 + 英语',
        free_btn: '免费获取 Waltly',
        pro_name: 'Pro 解锁', pro_sub: '一次付费。限时发布价 — 截至 2026 年 5 月 31 日。',
        pro_f1: '包含免费版所有功能', pro_f2: '无限钱包和分类', pro_f3: '小组件 + 控制中心快速记账', pro_f4: '旅行和活动基金', pro_f5: '循环预算模板', pro_f6: 'iCloud 同步（端到端加密）', pro_f7: 'CSV 导出',
        pro_btn: '解锁 Pro — Rp 79,000',
        faq_eye: '常见问题', faq_title: '问题，已解答。',
        faq1_q: 'Waltly 会连接我的银行吗？', faq1_a: '不会 — 这是有意为之的设计。印度尼西亚银行不提供干净的开发者 API，屏幕抓取既脆弱又存在风险。你通过小组件手动记录交易（2次点击），因此你的财务数据永远不会离开你的手机。',
        faq2_q: '真的是一次付费吗？', faq2_a: '是的。支付 Rp 79,000 一次，Pro 就永久属于你 — 在所有使用你 Apple ID 登录的 iOS 设备上。无需续费，无隐藏收费。',
        faq3_q: '支持 Android 吗？', faq3_a: 'Waltly 是 iOS 优先打造，充分利用小组件、控制中心、待机模式和 SwiftUI 特性。Android 计划于 2027 年推出。',
        faq4_q: '可以导出数据吗？', faq4_a: '当然可以。Pro 用户随时可以将完整交易记录导出为 CSV。数据属于你 — 如果你离开，所有数据都带走。',
        faq5_q: '支持哪些语言？', faq5_a: '发布时支持印度尼西亚语和英语，每个标签、提示和文案均为原生编写，非机器翻译。更多语言将根据用户投票陆续推出。',
        final_h2: '开始管理你的钱。<br>就是今天。',
        final_p: '永久免费。准备好了就升级到 Pro。支持 iPhone 和 iPad。',
        final_btn: '在 App Store 下载',
        legal_eye: '法律信息',
        privacy_title: '隐私政策', privacy_updated: '最后更新：2026年4月18日',
        privacy_p1: 'Waltly不会收集、存储或向外部服务器传输任何个人数据。',
        privacy_p2: '您输入的所有财务数据——包括交易记录、钱包、预算和目标——均使用Apple原生框架存储在您的设备本地。除非您主动导出，否则您的数据永远不会离开设备。',
        privacy_nouse_h: '我们不使用的内容', privacy_li1: '分析或追踪工具', privacy_li2: '广告网络', privacy_li3: '收集数据的第三方SDK', privacy_li4: '传输个人信息的崩溃报告服务',
        privacy_noacct_h: '无需账户', privacy_noacct_p: '我们不要求您创建账户。',
        privacy_support_h: '支持联系方式', privacy_support_p: '如果您通过电子邮件联系我们寻求支持，我们仅会使用您的电子邮件地址来回复您的问题，不会在对话结束后保存。',
        privacy_apple_h: 'Apple与App Store', privacy_apple_p: 'Apple可能会根据其自身的隐私政策通过App Store收集某些使用数据，这与Waltly无关。',
        privacy_contact: '如有疑问，请联系：',
        terms_title: '使用条款', terms_updated: '最后更新：2026年4月18日',
        terms_intro: '下载或使用Waltly即表示您同意这些条款。',
        terms_license_h: '许可证', terms_license_p: 'Waltly授予您在Apple设备上使用本应用的个人、不可转让、非独占许可。您不得复制、修改、逆向工程或分发本应用。',
        terms_data_h: '您的数据', terms_data_p: '您在Waltly中输入的所有数据均属于您。我们无法访问这些数据。您有责任维护自己的备份。',
        terms_advice_h: '非财务建议', terms_advice_p: 'Waltly是个人预算工具。应用中的任何内容均不构成财务、投资或法律建议。财务决策请务必咨询专业人士。',
        terms_warranty_h: '免责声明', terms_warranty_p: 'Waltly按"现状"提供，不提供任何形式的保证。我们不保证应用无错误或不中断运行。',
        terms_liability_h: '责任限制', terms_liability_p: '在法律允许的最大范围内，Waltly及其开发者不对因使用本应用而产生的任何间接、偶发或后果性损害承担责任。',
        terms_changes_h: '条款变更', terms_changes_p: '我们可能随时更新这些条款。变更后继续使用应用即表示接受新条款。',
        terms_contact: '联系方式：',
        foot_privacy: '隐私政策', foot_terms: '服务条款', foot_support: '支持', foot_twitter: 'Twitter', foot_ig: 'Instagram',
    }
};

let lang = localStorage.getItem('hd-lang') || 'id';

function t(key) { return T[lang][key] || T.en[key] || key; }

function applyLang() {
    document.documentElement.lang = lang;
    document.title = t('page_title');
    document.querySelectorAll('[data-i18n]').forEach(el => el.textContent = t(el.dataset.i18n));
    document.querySelectorAll('[data-i18n-html]').forEach(el => el.innerHTML = t(el.dataset.i18nHtml));
    const m = LANG_META[lang];
    document.getElementById('lang-flag').textContent = m.flag;
    document.getElementById('lang-label').textContent = m.label;
    document.querySelectorAll('.lang-menu button').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });
    localStorage.setItem('hd-lang', lang);
}

window.setLang = function (l, e) {
    if (e) e.stopPropagation();
    lang = l;
    applyLang();
    document.getElementById('lang-menu').classList.remove('open');
};

window.toggleLangMenu = function (e) {
    e.stopPropagation();
    document.getElementById('lang-menu').classList.toggle('open');
};

document.addEventListener('click', () => {
    document.getElementById('lang-menu').classList.remove('open');
});

applyLang();
